/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Схема для описания курса
 */
export interface Course {
  /**
   * Уникальный идентификатор тренировки
   */
  slug?: string;
  /**
   * Название курса
   */
  title: string;
  /**
   * Полное описание курса
   */
  description: string;
  /**
   * Краткое описание курса
   */
  shortDescription?: string;
  /**
   * URL миниатюры курса
   */
  thumbnail: string;
  /**
   * URL основного изображения курса
   */
  image: string;
  /**
   * Является ли курс черновиком (неопубликованным)
   */
  draft: boolean;
  /**
   * Продолжительность курса в неделях
   */
  durationWeeks: number;
  /**
   * Список слагов ежедневных планов, входящих в курс
   */
  dailyPlans?: string[];
  /**
   * Список слагов планов питания, входящих в курс
   */
  mealPlans?: string[];
}
