/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Схема для описания ежедневного плана в рамках курса
 */
export interface DailyPlan {
  /**
   * Уникальный идентификатор тренировки
   */
  slug?: string;
  /**
   * Порядковый номер дня в курсе
   */
  dayNumber: number;
  /**
   * Порядковый номер недели в курсе
   */
  weekNumber: number;
  /**
   * Описание дня
   */
  description?: string;
  /**
   * Слаг курса, к которому относится этот ежедневный план
   */
  courseSlug: string;
  /**
   * ID разминки (slug Workout)
   */
  warmupId: string;
  /**
   * ID основной тренировки (slug Workout)
   */
  mainWorkoutId?: string;
  /**
   * ID плана питания (slug MealPlan)
   */
  mealPlanId: string;
  /**
   * Дополнительные блоки контента для этого дня
   */
  contentBlocks?: {
    /**
     * Тип блока контента
     */
    type: "text";
    /**
     * Текст блока контента
     */
    text: string;
  }[];
}
