/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Manifest {
  /**
   * List of paths to course content YAML files.
   */
  courses: string[];
  /**
   * List of paths to workout content YAML files.
   */
  workouts: string[];
  /**
   * List of paths to recipe content YAML files.
   */
  recipes: string[];
}
