/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Схема для описания плана питания
 */
export interface MealPlan {
  /**
   * Уникальный идентификатор тренировки
   */
  slug?: string
  /**
   * Название плана питания
   */
  title: string
  /**
   * Описание плана питания
   */
  description?: string
  /**
   * Слаг курса, к которому относится этот план питания
   */
  courseSlug: string
  /**
   * ID рецепта для завтрака (slug Recipe)
   */
  breakfastRecipeId: string
  /**
   * ID рецепта для обеда (slug Recipe)
   */
  lunchRecipeId: string
  /**
   * ID рецепта для ужина (slug Recipe)
   */
  dinnerRecipeId: string
}
