/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Схема для описания рецепта
 */
export interface Recipe {
  /**
   * Уникальный идентификатор тренировки
   */
  slug?: string
  /**
   * Название рецепта
   */
  title: string
  /**
   * Описание рецепта
   */
  description?: string
  /**
   * Время приготовления в минутах
   */
  preparationTimeMinutes: number
  /**
   * Количество калорий на порцию
   */
  calories?: number
  /**
   * Количество порций
   */
  servings: number
  /**
   * Сложность приготовления
   */
  difficulty: 'EASY' | 'MEDIUM' | 'HARD'
  /**
   * Без глютена
   */
  isGlutenFree: boolean
  /**
   * Без сахара
   */
  isSugarFree: boolean
  /**
   * Категории приема пищи
   *
   * @minItems 1
   */
  mealCategories: [
    'BREAKFAST' | 'LUNCH' | 'DINNER' | 'SNACK' | 'SALAD' | 'DESSERT' | 'SOUP',
    ...(
      | 'BREAKFAST'
      | 'LUNCH'
      | 'DINNER'
      | 'SNACK'
      | 'SALAD'
      | 'DESSERT'
      | 'SOUP'
    )[],
  ]
  /**
   * Список ингредиентов
   */
  ingredients: {
    /**
     * Название ингредиента
     */
    name: string
    /**
     * Вес в граммах
     */
    weightGrams?: number
    /**
     * Количество
     */
    quantity?: number
    /**
     * Единица измерения (например, 'шт', 'мл', 'чашка')
     */
    unit?: string
  }[]
}
