/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * CUID2 - Collision-resistant, URL-friendly unique identifier.
 */
export type Cuid = string;
/**
 * A unique, human-readable slug for identification (lowercase, alphanumeric, hyphens).
 */
export type Slug = string;

export interface WeeklyContentSchema {
  id: Cuid;
  title: string;
  /**
   * The start date of this content week (e.g., '2025-07-14' for Monday)
   */
  releaseDate: string;
  /**
   * References to daily plans for each of the 7 days of the week.
   *
   * @minItems 7
   * @maxItems 7
   */
  dailyPlans: [
    DailyPlanReference,
    DailyPlanReference,
    DailyPlanReference,
    DailyPlanReference,
    DailyPlanReference,
    DailyPlanReference,
    DailyPlanReference
  ];
}
export interface DailyPlanReference {
  /**
   * Day number within the week (1=Monday, 7=Sunday)
   */
  dayNumberInWeek: number;
  dailyPlanSlug: Slug;
  [k: string]: unknown;
}
