/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for weeks.yaml file that defines weekly metadata for subscription courses
 */
export interface WeeksConfiguration {
  /**
   * Array of week configurations for the subscription course
   *
   * @minItems 1
   */
  weeks: [
    {
      /**
       * Sequential week number in the course
       */
      weekNumber: number;
      /**
       * ISO 8601 datetime when this week becomes available to users
       */
      releaseAt: string;
    },
    ...{
      /**
       * Sequential week number in the course
       */
      weekNumber: number;
      /**
       * ISO 8601 datetime when this week becomes available to users
       */
      releaseAt: string;
    }[]
  ];
}
