/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Схема для описания тренировки
 */
export interface Workout {
  /**
   * Уникальный идентификатор тренировки
   */
  slug?: string;
  /**
   * Название тренировки
   */
  title: string;
  /**
   * Тип тренировки
   */
  type: "WARMUP" | "POSTURE" | "STRENGTH" | "MOBILITY" | "CARDIO";
  /**
   * Длительность тренировки в минутах
   */
  durationMinutes: number;
  /**
   * Сложность тренировки
   */
  difficulty: "EASY" | "MEDIUM" | "HARD";
  /**
   * Список необходимого инвентаря
   */
  equipment: string[];
  /**
   * Описание тренировки
   */
  description?: string;
  /**
   * URL видео с тренировкой
   */
  videoId?: string;
  /**
   * Список задействованных групп мышц
   */
  muscles: ("LEGS" | "GLUTES" | "UPPER_BODY" | "BACK" | "PELVIC_FLOOR" | "CORE")[];
}
